{"name": "OOP: 6.5.11", "url": "https://stepik.org/lesson/933767/step/11", "tests": [{"id": 0, "input": "with Suppress(NameError):\n    print('\u042d\u0442\u043e\u0439 \u043f\u0435\u0440\u0435\u043c\u0435\u043d\u043d\u043e\u0439 \u043d\u0435 \u0441\u0443\u0449\u0435\u0441\u0442\u0432\u0443\u0435\u0442 -->', variable)\n    \nprint('\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u0435 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u044b')", "output": "\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u0435 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u044b"}, {"id": 1, "input": "with Suppress(TypeError, ValueError) as context:\n    number = int('\u044f \u0447\u0438\u0441\u043b\u043e')\n\nprint(context.exception)\nprint(type(context.exception))", "output": "invalid literal for int() with base 10: '\u044f \u0447\u0438\u0441\u043b\u043e'\n<class 'ValueError'>"}, {"id": 2, "input": "with Suppress() as context:\n    print('All success!')\n\nprint(context.exception)", "output": "All success!\nNone"}, {"id": 3, "input": "with Suppress(ValueError) as context:\n    try:\n        number = list(123)\n    except TypeError:\n        pass\n\nprint(context.exception)", "output": "None"}, {"id": 4, "input": "iterable = iter(range(100))\n\nwith Suppress(StopIteration) as context:\n    for _ in range(99):\n        next(iterable)\n    print(next(iterable))\n    print(next(iterable))\n\n\nprint(context.exception)\nprint(type(context.exception))", "output": "99\n\n<class 'StopIteration'>"}, {"id": 5, "input": "d = {'Gvido': 67, 'Gates': 67, 'Zuckerberg': 38}\nwith Suppress(KeyError) as context:\n    print(d['Mask'])\n\n\nprint(context.exception)\nprint(type(context.exception))", "output": "'Mask'\n<class 'KeyError'>"}, {"id": 6, "input": "with Suppress(ValueError) as context:\n    try:\n        print('\u041d\u0435\u0441\u0443\u0449\u0435\u0441\u0442\u0432\u0443\u044e\u0449\u0438\u0439 \u043c\u0435\u0442\u043e\u0434 \u0443 \u0441\u043b\u043e\u0432\u0430\u0440\u044f \u2013>', {}.new())\n    except AttributeError as e:\n        print(type(e))\n\nprint(context.exception)", "output": "<class 'AttributeError'>\nNone"}, {"id": 7, "input": "try:\n    with Suppress(ValueError) as context:\n        number = list(123)\nexcept TypeError:\n    pass\n\nprint(context.exception)", "output": "None"}], "interactive": false, "memoryLimit": 256, "timeLimit": 15000, "srcPath": "c:\\Users\\asald\\Documents\\OOP\\Module_6\\Module_6.5\\Module_6.5.11\\problem.py", "group": "OOP"}